[package]
name = "isopipe"
version = "0.0.1"
authors = ["alejandrogzi <alejandrxgzi@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Hillerlab master annotation pipeline package"
homepage = "https://github.com/alejandrogzi/isopipe"
repository = "https://github.com/alejandrogzi/isopipe"
readme = "README.md"
keywords = ["iso-seq", "bioinformatics", "genomics", "pipeline"]
categories = ["command-line-utilities", "science"]

[dependencies]
clap = { version = "4.0", features = ["derive"] }
simple_logger = { version = "4.0.0", optional = true }
memmap2 = { version = "0.9.5", optional = true }
serde = { version = "1.0.210", features = ["derive", "rc"], optional = true }
log = { version = "0.4.14", optional = true }
rayon = { version = "1.8.0", optional = true }
num_cpus = { version = "1.16.0" }
hashbrown = { version = "0.14", features = ["rayon"] }
time = { version = "0.3.36", optional = true }
toml = { version = "0.8.20", features = ["parse"], default-features = false }
chrono = { version = "0.4.40", optional = true }
twobit = { version = "0.2.1", optional = true }
dashmap = { version = "6", features = ["rayon"], optional = true }
iso-fusion = { path = "../isotools/isotools/iso-fusion", optional = true }
iso-pack = { path = "../isotools/isotools/iso-pack", optional = true }
config = { path = "../isotools/isotools/config", optional = true }
iso-polya = { path = "../isotools/isotools/iso-polya", optional = true }
isotools = { path = "../isotools/isotools/entry", optional = true }
iso-split = { path = "../isotools/isotools/iso-split", optional = true }

[profile.release]
lto = true
opt-level = 3

[features]
default = ["cfg", "core"]
cfg = ["dep:memmap2", "dep:serde", "dep:log", "dep:chrono"]
core = [
    "dep:rayon",
    "dep:dashmap",
    "dep:iso-fusion",
    "dep:iso-pack",
    "dep:config",
    "dep:iso-polya",
    "dep:isotools",
    "dep:iso-split",
    "dep:twobit",
    "dep:simple_logger",
]
