[metadata]
name = "isopipe"
version = "0.0.1"
authors = "alejandrogzi <alejandrxgzi@gmail.com>"
repository = "https://github.com/alejandrogzi/isopipe"
readme = "README.md"
run_id = ""

[packages]
lima = "1.11.0"
pbccs = "6.4.0"
isoseq3 = ""
minimap3 = ""
isotools = "0.0.1"
pbindex = "1.7.0"

[global]
data_prefix = "foo"                   # FILL: raw data prefix
global_output_dir = "/path/to/outdir" # FILL: output dir -> {outdir}/isopipe_run_{timestamp}
long_queue = "long"                   # long queue name
short_queue = "short"                 # short queue name
default_memory = 16                   # default memory in GB
default_threads = 8                   # default number of threads

[params.ccs]
chunk = 100              # --chunk
num-threads = 64         # -j
min-rq = 0.95            # --min-rq
report-file = "report"   # --report-file
output_dir = "step1_ccs" # output dir
input_dir = ""           # FILL: raw data dir [only one inmutable]
memory = 50              # memory in GB
time = "24.h"            # time for each job

[params.lima]
isoseq = ""               # leave empty and position
peek-guess = ""           # leave empty and position
primers = ""              # FILL: primers file
output_dir = "step2_lima" # output dir [default]
input_dir = "step1_ccs"   # raw data dir [default]
memory = 50               # memory in GB
time = "24.h"             # time for each job
num-threads = 64          # -j

[params.refine]
primers = ""                # FILL: primers file
output_dir = "step3_refine" # output dir
input_dir = "step2_lima"    # raw data dir [default]
memory = 50                 # memory in GB
num-threads = 64            # --num-threads
time = "24.h"               # time for each job


[params.cluster]

[params.filter-quality]
input_dir = "step4_cluster"         # raw data dir [default]
output_dir = "step5_filter_quality" # output dir
per_id = 0.96                       # --per_id
clip3 = 50                          # --clip3
suffix = 30                         # --suffix
memory = 50                         # memory in GB
time = "24.h"                       # time for each job
