//! Core module for extracting sequences using .2bit from a query set of reads
//! Alejandro Gonzales-Irribarren, 2025
//!
//! This module contains the main functions for efficiently getting whole
//! sequences from .2bit genomic files using plain coordinates. Additionally,
//! it provides the option of deduplicate repeated entries in order to save
//! space.
//!
//! In short, every sequence is extracted from a .2bit and holded in memory
//! as plain bytes for every read in the query set [rev comp for neg strand].
//! The command line interface provides the option of specifying indexing, leading
//! to a one-pass deduplication step and the creation of an index where
//! simple integers map to read identifiers [all of them as plain bytes].
//! The process is heavily parallelized to offer fast performance on large datasets.

use std::collections::HashMap;
use std::fs::File;
use std::io::{BufReader, Read};
use std::path::PathBuf;

/// Reads a binary index file generated by the `index` function and reconstructs
/// the mapping from new sequential IDs back to original read IDs.
///
/// The index file is expected to contain blocks of data. Each block starts with
/// a 2-byte `n_ids` (number of original IDs in the group), followed by a 4-byte
/// `header` (the new sequential ID for the unique sequence), and then `n_ids`
/// number of 4-byte original encoded read IDs.
///
/// This function reads these blocks, decodes the `u32` original IDs, formats
/// them back into a human-readable string (e.g., "R{id}_chr{chr}"), and stores
/// them in a `HashMap` where the key is the new sequential ID and the value
/// is a vector of original read ID strings that map to that unique sequence.
///
/// # Arguments
///
/// * `index` - A `PathBuf` representing the path to the binary index file.
/// * `chr` - A string slice representing the chromosome name. This is used to
///           reconstruct the full original read ID format (e.g., "R{id}_chr{chr}").
///
/// # Returns
///
/// A `HashMap<u32, Vec<String>>` where keys are the sequential IDs (headers)
/// and values are vectors of the original read ID strings associated with that sequential ID.
///
/// # Panics
///
/// This function will panic if:
/// - It fails to open the specified `index` file.
/// - It encounters an I/O error (e.g., incomplete read) during the process,
///   except when reaching the End-Of-File cleanly (which breaks the loop).
///
/// # Example
///
/// ```rust, no_run
/// use std::path::PathBuf;
/// use std::fs::File;
/// use std::io::{self, BufWriter, Write, Read};
/// use std::collections::HashMap;
/// use tempfile::NamedTempFile;
///
/// // Helper function to write a dummy index file for testing
/// fn create_dummy_index(path: &PathBuf) -> io::Result<()> {
///     let mut writer = BufWriter::new(File::create(path)?);
///
///     // Block 1: header 0, contains 2 IDs (R1, R2)
///     let n_ids1: u16 = 2;
///     writer.write_all(&n_ids1.to_be_bytes())?;
///     let header1: u32 = 0;
///     writer.write_all(&header1.to_be_bytes())?;
///     let id1_1: u32 = 1;
///     writer.write_all(&id1_1.to_be_bytes())?;
///     let id1_2: u32 = 2;
///     writer.write_all(&id1_2.to_be_bytes())?;
///
///     // Block 2: header 1, contains 1 ID (R3)
///     let n_ids2: u16 = 1;
///     writer.write_all(&n_ids2.to_be_bytes())?;
///     let header2: u32 = 1;
///     writer.write_all(&header2.to_be_bytes())?;
///     let id2_1: u32 = 3;
///     writer.write_all(&id2_1.to_be_bytes())?;
///
///     writer.flush()?;
///     Ok(())
/// }
///
/// let mut index_file = NamedTempFile::new().unwrap();
/// let index_path = index_file.path().to_path_buf();
///
/// create_dummy_index(&index_path).unwrap();
///
/// let chr_name = "chrX";
/// let result_map = read_index(&index_path, chr_name);
///
/// assert_eq!(result_map.len(), 2);
///
/// let group0 = result_map.get(&0).unwrap();
/// assert_eq!(group0.len(), 2);
/// assert!(group0.contains(&"R1_chrX".to_string()));
/// assert!(group0.contains(&"R2_chrX".to_string()));
///
/// let group1 = result_map.get(&1).unwrap();
/// assert_eq!(group1.len(), 1);
/// assert!(group1.contains(&"R3_chrX".to_string()));
///
/// // Clean up temporary file
/// index_file.close().unwrap();
/// ```
#[cfg(feature = "read")]
pub fn read_index(index: &PathBuf, chr: &str) -> HashMap<u32, Vec<String>> {
    let mut mapper = HashMap::new();

    let mut reader = BufReader::new(
        File::open(index).unwrap_or_else(|e| panic!("ERROR: failed to open index -> {e}")),
    );

    loop {
        let mut id_count_buf = [0u8; 2];
        if reader.read_exact(&mut id_count_buf).is_err() {
            break; // EOF reached cleanly
        }
        let n_ids = u16::from_be_bytes(id_count_buf);

        let mut header_buf = [0u8; 4];
        reader.read_exact(&mut header_buf).unwrap();
        let header = u32::from_be_bytes(header_buf);

        let mut id_buf = [0u8; 4];
        let mut group = Vec::with_capacity(n_ids as usize);
        for _ in 0..n_ids {
            reader.read_exact(&mut id_buf).unwrap();
            let id = u32::from_be_bytes(id_buf);

            // WARN: id fmt -> R{int}_chr{chr}, skipping tags!
            let name = format!("R{}_{}", id, chr);
            group.push(name);
        }

        mapper.entry(header).or_insert_with(Vec::new).extend(group);
    }

    mapper
}
