[build-system]
requires = [
    "setuptools>=42.0",
    "wheel",
    "Cython>=0.29.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "orfipy"
dynamic = ["version"]
description = "orfipy"
readme = {file = "README.md", content-type = "text/markdown"}
authors = [
    {name = "Urminder Singh", email = "usingh@iastate.edu"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Unix",
]
keywords = ["bioinformatics", "orfs", "genomics"]
dependencies = [
    "cython",
    "psutil",
    "pyfastx",
    "pyahocorasick",
    "colorama"
]
requires-python = ">=3.5,<3.10"

[project.urls]
Homepage = "https://github.com/urmi-21/orfipy"
Repository = "https://github.com/urmi-21/orfipy"

[project.scripts]
orfipy = "orfipy.__main__:main"

[tool.setuptools]
include-package-data = true
packages = {find = {}}

[tool.setuptools.dynamic]
version = {attr = "orfipy.version.__version__"}
