table isopipe
"Schema for isopipe-produced long-read transcriptomic reads"
(
    string  chrom;              "Reference sequence chromosome or scaffold"
    uint    chromStart;         "Start position of feature on chromosome"
    uint    chromEnd;           "End position of feature on chromosome"
    string  name;               "Feature ID"
    uint    score;              "Score (0-1000)"
    char[1] strand;             "+ or - for strand"
    uint    thickStart;         "Coding region start"
    uint    thickEnd;           "Coding region end"
    uint    itemRgb;           "RGB color value"
    int     blockCount;         "Number of exons"
    int[blockCount] blockSizes; "Exon sizes"
    int[blockCount] chromStarts;"Exon starts relative to chromStart"

    string  R_read_status;              "R: Read status"
    lstring R_read_intron_status;       "R: Intron status"
    lstring R_metadata_html;            "R: Metadata in HTML"
    lstring R_retentions_html;          "R: Retention introns in HTML"
    lstring R_retains_rt_intron_html;   "R: RT intron retention in HTML"
    lstring R_rt_html;                  "R: Reverse transcription events in HTML"
    string  P_read_status;              "P: Read status"
    lstring P_metadata_html;            "P: Metadata in HTML"
    string  T_read_status;              "T: Read status"
    lstring T_metadata_html;            "T: Metadata in HTML"
    float   O_read_orf_score;           "O: ORF score"
    lstring O_metadata_html;            "O: Metadata in HTML"

    int     TAG_five_clip_len;          "Length of 5' clipping"
    int     TAG_three_clip_len;         "Length of 3' clipping"
    int     TAG_polya_len;              "PolyA tail length"
    int     TAG_polya_read_len;         "Length of read contributing to PolyA"
    int     TAG_mapping_identity;       "Mapping identity (%)"
    string    TAG_singleton;              "Singleton read flag"
    int     TAG_orf_number;             "Number of ORFs"
    string   TAG_nested_orf_number;      "Number of nested ORFs"
    string    TAG_fake_fusion;            "Fake fusion flag"
    string    TAG_review_fusion;          "Fusion under review flag"
    string    TAG_strong_nmd;             "Strong NMD prediction"
    string    TAG_weak_nmd;               "Weak NMD prediction"
    string    TAG_unique_tai;               "Unique translationAi prediction"
)
