[package]
name = "extract"
version = "0.0.7"
edition = "2024"
authors = ["alejandrogzi <alejandrxgzi@gmail.com>"]
license = "MIT"
description = "Extract sequences from .2bit using .bed [and index them]"
homepage = "https://github.com/alejandrogzi/isopipe"
repository = "https://github.com/alejandrogzi/isopipe"
readme = "README.md"
keywords = ["iso-seq", "bioinformatics", "genomics", "pipeline"]
categories = ["command-line-utilities", "science"]

[dependencies]
iso-pack = { path = "../../../modules/isotools/isotools/iso-pack", optional = true }
config = { path = "../../../modules/isotools/isotools/config", optional = true }
iso-polya = { path = "../../../modules/isotools/isotools/iso-polya", optional = true }
clap = { version = "4.0", features = ["derive"], optional = true }
simple_logger = { version = "4.0.0", optional = true }
rayon = { version = "1.8.0", optional = true }
log = { version = "0.4.14", optional = true }
num_cpus = { version = "1.16.0", optional = true }
dashmap = { version = "6", features = ["rayon"], optional = true }

[profile.release]
lto = true
opt-level = 3

[features]
default = ["core"]
read = []
core = [
    "dep:num_cpus",
    "dep:clap",
    "dep:rayon",
    "dep:iso-pack",
    "dep:config",
    "dep:iso-polya",
    "dep:simple_logger",
    "dep:log",
    "dep:dashmap",
]
