[package]
name = "collapse"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
simple_logger = { version = "5.0.0" }
log = { version = "0.4.14" }
num_cpus = "1.16.0"
rayon = "1.8.1"
once_cell = "1.21.3"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }
